# Generated by Django 5.1.3 on 2024-12-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_doctor_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
    ]
